#!/bin/bash

if [ "$1" = "clean" ]; then
    rm -f scheduler
    echo "[!] Cleaned build artifacts"
    exit 0
fi

if [ "$1" = "gdb" ]; then
    gcc core/main.c -o scheduler
    gdb -tui scheduler
    exit 0
fi

echo "[+] building scheduler"
gcc core/main.c -o scheduler
./scheduler
